import os, re

PATTERNS = {
    "// Step N":                  r"//\s*Step\s+\d",
    "// Helper function":         r"//\s*Helper\s+function",
    "// This function":           r"//\s*This\s+function",
    "// First/Then/Finally/etc":  r"//\s*(First|Then|Finally|Now we|Let'?s)\b",
    "<!-- Begin/End section -->": r"<!--\s*(Begin|End|Start)\s",
    "AI generator meta tag":      r'<meta[^>]*name=["\']generator["\']',
    "Tracking attributes":        r"data-(telemetry|tracking|analytics)",
    "ChatGPT/AI signature":       r"(ChatGPT|generated by|created with AI)",
}

EXTS = (".js", ".html", ".css", ".md")
SKIP = ("node_modules", ".git", "storage", "graphify-out", "database/schema")

hits = {k: 0 for k in PATTERNS}
top  = {k: [] for k in PATTERNS}

for root, dirs, files in os.walk("."):
    dirs[:] = [d for d in dirs if not any(s in os.path.join(root, d) for s in SKIP)]
    for f in files:
        if not f.endswith(EXTS):
            continue
        path = os.path.join(root, f)
        try:
            with open(path, encoding="utf-8", errors="ignore") as fp:
                txt = fp.read()
        except Exception:
            continue
        for name, pat in PATTERNS.items():
            n = len(re.findall(pat, txt, re.IGNORECASE))
            if n:
                hits[name] += n
                top[name].append((path, n))

print("Scan signatures IA")
print("==================")
for name, n in hits.items():
    if n == 0:
        print(f"  OK  {name}")
    else:
        worst = sorted(top[name], key=lambda x: -x[1])[0]
        rel = worst[0].replace("\\", "/").lstrip("./")
        print(f"  {n:4d} x  {name}  (top: {rel})")
